# kakrc

# colors

colorscheme mochi

# plugins

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "alexherbo2/connect.kak"

plug "eraserhd/parinfer-rust" do %{
    cargo build --release
    cargo install --force --path .
}

# highlighters

add-highlighter global/ regex \b(todo|note)\b 0:todo
add-highlighter global/ number-lines -separator ' '
# add-highlighter global/ show-matching

# keys

# map global insert <a-backspace> '<esc>xHdi'
# map global insert <tab> '<a-;><a-gt>'
# map global insert <s-tab> '<a-;><lt>'

# map global normal <ret> '<a-o>j'
# map global normal D 'xHd'

map global normal ( [
map global normal [ (
map global normal ) ]
map global normal ] )

map global normal <a-(> <a-[>
map global normal <a-[> <a-(>
map global normal <a-)> <a-]>
map global normal <a-]> <a-)>

# map global user m '"jZ'
# map global user \' '"jzvc'

# options

set global indentwidth 2

# hook global WinSetOption filetype=c {
  # set buffer indentwidth 4
# }

hook global InsertChar '\t' %{
  execute-keys -draft "h%opt{indentwidth}@"
}

set global ui_options ncurses_assistant=cat
set global autocomplete prompt

# commands

define-command editrc %{
  cd '~/.config/kak'
}

alias global erc editrc

define-command vertical-split -params .. -file-completion %{
  tmux-terminal-vertical kak -c %val(session) %arg(@)
}

define-command horizontal-split -params .. -file-completion %{
  tmux-terminal-horizontal kak -c %val(session) %arg(@)
}

alias global vsp vertical-split
alias global hsp horizontal-split

# define-command aplay %{
#   eval -draft -save-regs '/"|^@' %{
#     exec 's[^"()[\]{}]+<ret>'
#     nop %sh{
#       (mpc-prev.sh "$kak_selection") < /dev/null > /dev/null 2>&1 &
#     }
#   }
# }

# define-command astop %{
#   nop %sh{ killall aplay }
# }

# map global user p ': aplay<ret>'
# map global user <esc> ': astop<ret>'

define-command hlcomments %{
  addhl buffer/_comments regions
  addhl buffer/_comments/comments region '#' '$' fill comment
}

# clear scratch buffer
hook -always -once global WinCreate '\Q*scratch*' %{
  exec '%<a-d>'
}

# hook -always global ClientCreate .* %{
#  hook global FocusOut .* %{
#    face buffer PrimarySelection default,default+F
#    face buffer PrimaryCursor default,default+F
#    face buffer PrimaryCursorEol default,default+F
#    face buffer SecondarySelection default,default+F
#    face buffer SecondaryCursor default,default+F
#    face buffer SecondaryCursorEol default,default+F
#  }
#
#  hook global FocusIn .* %{
#    # todo actually set old faces
#    colorscheme mochi
#  }
#}
