colorscheme mochi

add-highlighter global/ regex \b(todo|note)\b 0:todo

add-highlighter global/ number-lines -separator ' '
# add-highlighter global/ show-matching

map global insert <a-backspace> '<esc>xHdi'
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

map global normal <ret> '<a-o>j'
map global normal D 'xHd'

map global normal ( [
map global normal [ (
map global normal ) ]
map global normal ] )

map global normal <a-(> <a-[>
map global normal <a-[> <a-(>
map global normal <a-)> <a-]>
map global normal <a-]> <a-)>

map global user s ': send-text<ret>'

set global indentwidth 2
set global ui_options ncurses_assistant=cat
set global autocomplete prompt

define-command editrc %{
  cd '~/.config/kak'
}

define-command vertical-split %{
  eval tmux-terminal-vertical kak -c %val{session}
}

define-command horizontal-split %{
  eval tmux-terminal-horizontal kak -c %val{session}
}

require-module tmux-repl

alias global vertical-cd   tmux-repl-vertical
alias global horizontal-cd tmux-repl-horizontal

# define-command aplay %{
  # eval -draft -save-regs '/"|^@' %{
    # exec 's[^"()[\]{}]+<ret>'
    # nop %sh{
      # (mpc-prev.sh "$kak_selection") < /dev/null > /dev/null 2>&1 &
    # }
  # }
# }

# define-command astop %{
  # nop %sh{ killall aplay }
# }

# map global user p ': aplay<ret>'
# map global user <esc> ': astop<ret>'

define-command hlcomments %{
  addhl buffer/_comm regions
  addhl buffer/_comm/comments region '#' '$' fill comment
}
