xset r rate 360 30
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Profile Enabled" 0 1
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Wheel Emulation Timeout" 150
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Wheel Emulation Axes" 6 7 4 5
xrdb ~/.Xresources
# export _JAVA_AWT_WM_NONREPARENTING=1
