[[ -f ~/.bashrc ]] && . ~/.bashrc

export LANG=en_US.utf8
export EDITOR='nvim'

export PATH=$PATH:'/home/mel/dotfiles/_wm/lemons'
export XDG_CONFIG_HOME=~/.config

export ALSA_CARD=Generic

export LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib
export LS_COLORS='di=1;34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=1;34:ow=1;34'
