[[ $- != *i* ]] && return

HISTCONTROL=ignoredups

exitstatus() {
  if [[ $? == 0 ]]; then
    echo -e "oo)/"
  else
    echo -e "\e[1;31m$?)/\e[0m"
  fi
}

pdir() {
  pwd | home
}

PS1='$(exitstatus) \[\e[32m\]$(pdir) \[\e[1;30m\]> \[\e[0m\]'

printcolor() {
  # standard colors
  for C in {40..47}; do
      echo -en "\e[${C}m$C "
  done

  # high intensity colors
  for C in {100..107}; do
      echo -en "\e[${C}m$C "
  done

  echo -e "\e(B\e[m"
}

# pacman
alias inst='sudo pacman -S'
alias uninst='sudo pacman -Rs'
alias update='sudo pacman -Syu'

# X11
alias sx1='startx ~/dotfiles/_sessions/monsterwm'
alias sx2='startx ~/dotfiles/_sessions/openbox'
alias xresc='xrdb ~/.Xresources'
alias split='(urxvt &)'
alias coffee='systemd-inhibit --what=handle-lid-switch cat'

# sys
alias rm='rm -I'
alias top='htop'
alias mount='sudo mount'
alias umount='sudo umount'
alias _ls='ls -1NLv --group-directories-first --color=always'
alias ls='echo -en "\e[7m\e[32m\e[1m"; pwd; echo -en "\e[0m"; _ls'
alias ks='ls'
alias sl='ls'

#alias r='ranger'
alias am='alsamixer'
alias conn='sudo netctl stop-all; sudo netctl start'

alias clrram='sudo zsh -c "free -h && sync && echo 3 > /proc/sys/vm/drop_caches && free -h"'
alias clrtmp='for i in /tmp/* ; do sudo rm -r "$i" ; done'
alias clrcoredumps='sudo rm /var/lib/systemd/coredump/*'
alias clrall='clrram; clrtmp; clrcoredumps'

alias hddsleep='sudo hdparm -Y'
alias hds='hddsleep /dev/sdb'

# chicken
alias csi='rlwrap csi -q'
alias chicken-install='sudo chicken-install'
alias chicken-uninstall='sudo chicken-uninstall'

# goto
alias '@wm'='cd ~/dotfiles/_wm'
alias '@miri'='cd ~/documents/programming/c/miri7/src'
alias '@regu'='cd ~/documents/programming/c/libregu/src'
alias '@hive'='cd ~/documents/programming/hive/desktop/src'
alias '@smake'='cd ~/documents/programming/scheme/smake'
alias '@orth'='cd ~/documents/programming/c/orth/src'

# other
alias sxiv='sxiv -a'
alias umpv='~/dotfiles/_wm/scripts/umpv.py'
alias youtube-dl='youtube-dl --no-playlist'
alias mpcclip='mpc -f "%artist% %title%" | head -1 | xclip -i -selection clipboard'
alias batt='cat /sys/class/power_supply/BAT1/capacity'
