export LANG=en_US.utf8
export EDITOR='nvim'
export PATH=$PATH:'/home/mel/dotfiles/_wm/lemons'
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib
export XDG_CONFIG_HOME=~/.config
export ALSA_CARD=Generic
export RANGER_LOAD_DEFAULT_RC=false
export CHICKEN_DOC_COLORS=auto

export PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
