alias pacman='sudo pacman'
alias mount='sudo mount'
alias umount='sudo umount'

alias sx1='startx ~/dotfiles/_wm/sessions/dwm'

alias rm='rm -I'

alias _ls='ls -1NLv --group-directories-first --color=auto'
alias ls='printf "\e[1;32;7m%s\e[0m\n" $(pwd); _ls'
export LS_COLORS='di=1;34:fi=39:ow=1;34'

alias pdf='zathura'
alias e='emacsclient -nw'
alias am='alsamixer'
alias conn='sudo netctl stop-all; sudo netctl start'
alias top='htop'

alias hddsleep='sudo hdparm -Y'
alias hds='hddsleep /dev/sdb'

alias sbcl='rlwrap sbcl'

alias sxiv='sxiv -a'
alias ydl='youtube-dl --no-playlist'
alias mpcclip='mpc -f "%artist% %title%" | head -1 | xclip -i -selection clipboard'

export PS1='$ '
